#!/usr/bin/env bash
# lang.sh — строки интерфейса меню. Подключается из menu.sh.
# Добавить язык: скопировать блок и перевести значения.

declare -A T

ui_lang_load() {
    if [[ "${1:-ru}" == "en" ]]; then
        T=(
            [subtitle]="· per-user speed limiter"
            [choice]="Choice"
            [back]="Enter — back"
            [cancel]="Cancel"
            [cancelled]="Cancelled."
            [need_num]="A number is required"
            [need_root]="Root privileges required: sudo shaper"

            [st_shaper]="Shaper   "
            [st_running]="running"
            [st_stopped]="stopped"
            [st_iface]="interface"
            [st_nolimit]="traffic is not limited"
            [st_auto]="Autostart"
            [st_auto_on]="enabled"
            [st_auto_off]="disabled"
            [st_auto_ok]="survives a server reboot"
            [st_auto_warn]="no limit after a reboot!"
            [st_speed]="Speed    "
            [st_unlimited]="unlimited"
            [st_peruser]="per user"
            [st_port]="Port     "
            [st_all]="ALL"

            [m1]="Set limit"
            [m1d]="— speed and port"
            [m2]="Monitor"
            [m2d]="— who is loading the channel right now"
            [m3]="Statistics"
            [m3d]="— total traffic per IP"
            [m4]="IP whitelist"
            [m5]="Service"
            [m5d]="— start, autostart, logs, update"
            [m0]="Exit"

            [lim_title]="Speed per user"
            [lim_h1]="The limit applies to each IP separately, in both directions."
            [lim_h2]="Fifty users at 15 Mbit/s means up to 750 Mbit/s on the channel."
            [lim_d10]="1080p video, saves bandwidth"
            [lim_d15]="comfortable for most people"
            [lim_d20]="generous, 4K plays smoothly"
            [lim_own]="Enter a custom value"
            [lim_off]="Remove the limit"
            [lim_ask]="Speed, Mbit/s"
            [port_h1]="The port your clients connect to. On a Remnawave node"
            [port_h2]="it is almost always 443. Several — comma separated, 0 = all."
            [listening]="Ports currently listened on:"
            [port_ask]="Port"
            [conf_off]="The limit will be removed, traffic will flow freely."
            [conf_on1]="Limit"
            [conf_on2]="per user, port"
            [apply_q]="Apply? [Y/n]"

            [stats_title]="Statistics"
            [stats_d1]="How much each IP has transferred since the shaper started."
            [stats_d2]="For the current load see «Monitor»."
            [stats_top]="Show (top 20)"
            [stats_full]="Full IP list"

            [wl_title]="Whitelist"
            [wl_d]="These IPs bypass the shaper: your own address, monitoring, panel."
            [wl_add]="Add IP"
            [wl_del]="Remove IP"
            [wl_ask]="IP address"

            [sv_title]="Service"
            [sv_start]="Start"
            [sv_stop]="Stop"
            [sv_restart]="Restart"
            [sv_restart_d]="(rebuild eBPF)"
            [sv_auto]="Autostart:"
            [sv_to_off]="— press to disable"
            [sv_to_on]="— press to enable"
            [sv_logs]="Logs"
            [sv_doctor]="Check environment"
            [sv_update]="Update from GitHub"
            [sv_lang]="Язык / Language"
            [sv_auto_yes]="autostart enabled"
            [sv_auto_no]="autostart disabled — no limit after a reboot"
            [sv_version]="version"

            [up_title]="Update from GitHub"
            [up_src]="Source:"
            [up_installed]="Installed version:"
            [up_git]="Installing git…"
            [up_nogit]="could not install git"
            [up_dl]="Downloading…"
            [up_fail]="download failed — check your internet and the repository URL"
            [up_latest]="already the latest version"
            [up_new]="New version:"
            [up_changes]="Recent changes:"
            [up_k1]="Settings and whitelist are preserved. During the update the"
            [up_k2]="shaper restarts — client connections are not dropped, the speed"
            [up_k3]="limit is simply lifted for a couple of seconds."
            [up_q]="Update? [y/N]"
            [up_backup]="Backup of the current version:"

            [dr_title]="Environment check"
            [dr_kernel]="Linux kernel     "
            [dr_need]="5.4+ required"
            [dr_notinst]="not installed"
            [dr_bpffs]="bpffs            "
            [dr_mounted]="mounted"
            [dr_notmounted]="not mounted"
            [dr_iface]="Uplink interface "
            [dr_undetected]="not detected"
            [dr_qdisc]="Root qdisc       "
            [dr_maps]="Maps pinned      "
            [dr_nosvc]="no (service is not running)"

            [lang_title]="Choose language"
            [lang_saved]="Language saved"
        )
    else
        T=(
            [subtitle]="· ограничитель скорости на пользователя"
            [choice]="Выбор"
            [back]="Enter — назад"
            [cancel]="Отмена"
            [cancelled]="Отменено."
            [need_num]="Нужно число"
            [need_root]="Нужны права root: sudo shaper"

            [st_shaper]="Шейпер   "
            [st_running]="работает"
            [st_stopped]="остановлен"
            [st_iface]="интерфейс"
            [st_nolimit]="трафик не ограничивается"
            [st_auto]="Автостарт"
            [st_auto_on]="включён"
            [st_auto_off]="выключен"
            [st_auto_ok]="переживёт перезагрузку сервера"
            [st_auto_warn]="после ребута лимита не будет!"
            [st_speed]="Скорость "
            [st_unlimited]="не ограничена"
            [st_peruser]="на каждого пользователя"
            [st_port]="Порт     "
            [st_all]="ВСЕ"

            [m1]="Настроить лимит"
            [m1d]="— скорость и порт"
            [m2]="Монитор"
            [m2d]="— кто грузит канал прямо сейчас"
            [m3]="Статистика"
            [m3d]="— сколько прокачали всего"
            [m4]="Белый список IP"
            [m5]="Сервис"
            [m5d]="— запуск, автостарт, логи, обновление"
            [m0]="Выход"

            [lim_title]="Скорость на одного пользователя"
            [lim_h1]="Лимит действует на каждый IP отдельно и в обе стороны."
            [lim_h2]="Пятьдесят человек по 15 Мбит/с — это до 750 Мбит/с на канал."
            [lim_d10]="видео 1080p, экономия канала"
            [lim_d15]="комфорт для большинства"
            [lim_d20]="с запасом, 4K не тормозит"
            [lim_own]="Ввести своё значение"
            [lim_off]="Снять ограничение"
            [lim_ask]="Скорость, Мбит/с"
            [port_h1]="Порт, на который подключаются клиенты. В Remnawave-ноде"
            [port_h2]="это почти всегда 443. Несколько — через запятую, 0 = все."
            [listening]="Порты, которые сейчас слушают процессы:"
            [port_ask]="Порт"
            [conf_off]="Ограничение будет снято, трафик пойдёт свободно."
            [conf_on1]="Лимит"
            [conf_on2]="на каждого пользователя, порт"
            [apply_q]="Применить? [Y/n]"

            [stats_title]="Статистика"
            [stats_d1]="Сколько каждый IP прокачал за всё время работы шейпера."
            [stats_d2]="Кто грузит канал прямо сейчас — смотри «Монитор»."
            [stats_top]="Показать (топ-20)"
            [stats_full]="Полный список IP"

            [wl_title]="Белый список"
            [wl_d]="Эти IP минуют шейпер: свой адрес, мониторинг, панель."
            [wl_add]="Добавить IP"
            [wl_del]="Убрать IP"
            [wl_ask]="IP-адрес"

            [sv_title]="Сервис"
            [sv_start]="Запустить"
            [sv_stop]="Остановить"
            [sv_restart]="Перезапустить"
            [sv_restart_d]="(пересобрать eBPF)"
            [sv_auto]="Автостарт:"
            [sv_to_off]="— нажми, чтобы выключить"
            [sv_to_on]="— нажми, чтобы включить"
            [sv_logs]="Логи"
            [sv_doctor]="Проверить окружение"
            [sv_update]="Обновить из GitHub"
            [sv_lang]="Язык / Language"
            [sv_auto_yes]="автостарт включён"
            [sv_auto_no]="автостарт выключен — после ребута лимита не будет"
            [sv_version]="версия"

            [up_title]="Обновление из GitHub"
            [up_src]="Источник:"
            [up_installed]="Установлена версия:"
            [up_git]="Ставлю git…"
            [up_nogit]="не удалось установить git"
            [up_dl]="Скачиваю…"
            [up_fail]="не скачалось — проверь интернет и адрес репозитория"
            [up_latest]="уже последняя версия"
            [up_new]="Новая версия:"
            [up_changes]="Последние изменения:"
            [up_k1]="Настройки и белый список сохранятся. На время обновления"
            [up_k2]="шейпер перезапустится — соединения клиентов не рвутся,"
            [up_k3]="на пару секунд просто снимется ограничение скорости."
            [up_q]="Обновить? [y/N]"
            [up_backup]="Копия текущей версии:"

            [dr_title]="Проверка окружения"
            [dr_kernel]="Ядро Linux       "
            [dr_need]="нужно 5.4+"
            [dr_notinst]="не установлен"
            [dr_bpffs]="bpffs            "
            [dr_mounted]="примонтирована"
            [dr_notmounted]="не примонтирована"
            [dr_iface]="Интерфейс наружу "
            [dr_undetected]="не определён"
            [dr_qdisc]="Корневой qdisc   "
            [dr_maps]="Карты закреплены "
            [dr_nosvc]="нет (сервис не запущен)"

            [lang_title]="Выбери язык"
            [lang_saved]="Язык сохранён"
        )
    fi
}
